### ISSUE TITLE
Creation of Docker.runner in XL-Deploy

### ISSUE THREAD

**Issue by yogendramummaneni** [xebialabs-community/xld-docker-plugin#1]
Hello,

I have installed the docker plugin in XL-Deploy-4.5.3

I am trying to configure docker.runner in Repository - Infrastructure
What exactly are the Server URL and Certificate Location?

Could you please also confirm that if there is docker plugin available for XL-Deploy 5.x?

Thanks,
Yogi.

**Comment by jdewinne** [comment]
Hi,

I've just released version 1.1.0:
https://github.com/xebialabs-community/xld-docker-plugin/releases/tag/v1.1.0

This release should work from 5.0.2+. And I've also updated the readme explaining what server url and certificate location should be.

Remark: v1.1.0, doesn't require the library dependencies and hotfix, as they are included in the xldp file.

Regards,
Joris
