### ISSUE TITLE
if tls-verify is unchecked commands should not fail looking for TLS variables

### ISSUE THREAD

**Issue by mickfeech** [xebialabs-community/xld-docker-plugin#9]
If TLS is unchecked jobs will fail if DOCKER_TLS_VERIFY and DOCKER_CERT_PATH are not set.  Furthermore, if TLS is unchecked and you don't supply a certificate path the job also fails because that item is empty.

```20170209T191940267/working.directory.tmp/docker-compose/up.sh
Executing /tmp/ot-20170209T191940267/working.directory.tmp/docker-compose/up.sh on host Infrastructure/Unix/server1
TLS configuration is invalid - make sure your DOCKER_TLS_VERIFY and DOCKER_CERT_PATH are set correctly.
You might need to run `eval "$(docker-machine env default)"`
Execution failed with exit code 1```

**Comment by bmoussaud** [comment]
@mickfeech thank you for this report. can you create a PR to fix it ? except this issue, does the plugin offer enough features ?
